///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsCloud = 'assets/icons/cloud.svg';
  static const String iconsGradus = 'assets/icons/gradus.svg';
  static const String iconsRainy = 'assets/icons/rainy.svg';
  static const String iconsSnowCloud = 'assets/icons/snow_cloud.svg';
  static const String iconsSun = 'assets/icons/sun.svg';
  static const String imagesImage = 'assets/images/image.png';

}
